### ISSUE TITLE
Invalid checkpoints link

### ISSUE THREAD

**Issue by lzhangbj** [v-iashin/Synchformer#1]
Hi Iashin,

Thanks for your great work on av-synchronization!
All links to config files and pretrained weights seem invalid. Could you please help update it? 

Thank you!

**Comment by v-iashin** [comment]
Could you please elaborate (or check again)? They work for me now

**Comment by lzhangbj** [comment]
Oh NVM, on browser, the error "This site can’t provide a secure connection" shows. I am using wget and it works well.

Thank you for your instant feedback!

**Comment by lzhangbj** [comment]
Seems to be problem of browser
