### ISSUE TITLE
Fixed offset in the training process

### ISSUE THREAD

**Issue by LoieSun** [v-iashin/Synchformer#4]
Hi, thank you for your very interesting work!

I have also recently tried to train a synchronization model, but I found that when I randomly set the offset and start_time during the training process, the model is more difficult to overfit. 

Also, I noticed that you used fixed offset during the training process. Have you encountered the same problem during training?

Thanks~

**Comment by v-iashin** [comment]
We haven’t used fixed offset during training of the synchronization module.
